wtf:
  colors:
    background: black
    border:
      focusable: darkslateblue
      focused: orange
      normal: lightblue
    # term: "xterm-256color"
  grid:
    # How _wide_ the columns are, in terminal characters.
    columns: [36, 38, 38, 38, 40]

    # How _high_ the rows are, in terminal lines.
    rows: [12, 12, 12, 4]
  refreshInterval: 1
  openFileUtil: xdg-open
  mods:
    ipinfo:
      colors:
        name: red
        value: white
      enabled: true
      position:
        top: 0
        left: 4
        height: 1
        width: 1
        refreshInterval: 15

    clocks:
      title: " ðŸ•— World Clocks "
      colors:
        rows:
          even: "lightblue"
          odd: "white"
      enabled: true
      locations:
        # From https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
        Sydney: "Australia/Sydney"
        Brisbane: "Australia/Brisbane"
        Adelaide: "Australia/Adelaide"
        Perth: "Australia/Perth"
        Belfast: "Europe/Belfast"
        Shanghai: "Asia/Shanghai"
        US/Pacific: "US/Pacific"
        UTC: "Etc/UTC"
      position:
        top: 0
        left: 0
        height: 1
        width: 1
      refreshInterval: 15
      # Valid options are: alphabetical, chronological
      sort: "chronological"

    hackernews:
      numberOfStories: 20
      storyType: top
      enabled: true
      position:
        top: 0
        left: 1
        height: 2
        width: 3
      refreshInterval: 900

    jira:
      title: " ðŸ“‚ Jira "
      colors:
        rows:
          even: "lightblue"
          odd: "white"
      domain: "https://kwelasolutions.atlassian.net"
      email: "colin@kwelasolutions.com"
      enabled: true
      jql: "resolution = Unresolved"
      position:
        top: 1
        left: 4
        height: 1
        width: 1
      project: "FOL"
      refreshInterval: 600
      username: "colin"
    security:
      title: " ðŸ¤º Security "
      enabled: true
      position:
        top: 1
        left: 0
        height: 2
        width: 1
      refreshInterval: 3600
    system:
      enabled: true
      position:
        top: 2
        left: 1
        height: 1
        width: 1
      refreshInterval: 3600
    prettyweather:
      enabled: true
      city: "sydney"
      colors:
        current: "lightblue"
      position:
        top: 2
        left: 2
        height: 1
        width: 1
      refreshInterval: 900

    git:
      commitCount: 14
      enabled: true
      position:
        top: 2
        left: 3
        height: 2
        width: 2
      refreshInterval: 8
      repositories:
        - "/home/colinbell/folio/src/240/"
        - "/home/colinbell/folio/src/230/"
        - "/home/colinbell/folio/deploy/rails4"
        - "/home/colinbell/.emacs.d/"

    cmdrunner:
      args: [""]
      cmd: "upuname"
      enabled: true
      position:
        top: 3
        left: 0
        height: 1
        width: 3
      refreshInterval: 30
